export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    THEME: 'THEME',
    STATUS: 'STATUS',
    MODAL: 'MODAL',
    SOCKET: 'SOCKET',
    ONLINE: 'ONLINE',
    OFFLINE: 'OFFLINE',
    CALL: 'CALL',
    PEER: 'PEER'
}

export const PROFILE_TYPES = {
    LOADING:'LOADING',
    GET_USER:'GET_USER',
    FOLLOW:'FOLLOW',
    UNFOLLOW:'UNFOLLOW',
    GET_ID:'GET_PROFILE_ID',
    GET_POSTS:'GET_PROFILE_POSTS',
    UPDATE_POSTS:'UPDATE_PROFILE_POSTS'
}

export const POST_TYPES = {
    CREATE_POST:'CREATE_POST',
    LOADING_POST:'LOADING_POST',
    GET_POSTS:'GET_POSTS',
    UPDATE_POST: 'UPDATE_POST',
    GET_POST: 'GET_POST',
    DELETE_POST: 'DELETE_POST'
}

export const DISCOVER_TYPES = {
    LOADING:'LOADING_DISCOVER',
    GET_POSTS:'GET_DISCOVER_POSTS',
    UPDATE_POST: 'UPDATE_DISCOVER_POST'
}

export const SUGGES_TYPES = {
    LOADING:'LOADING_SUGGES',
    GET_USERS:'GET_USERS_SUGGES'
}

export const NOTIFY_TYPES = {
    GET_NOTIFIES:'GET_NOTIFIES',
    CREATE_NOTIFY: 'CREATE_NOTIFY',
    REMOVE_NOTIFY: 'REMOVE_NOTIFY',
    UPDATE_NOTIFY: 'UPDATE_NOTIFY',
    UPDATE_SOUND: 'UPDATE_SOUND',
    DELETE_ALL_NOTIFIES: 'DELETE_ALL_NOTIFIES'
}

export const MESS_TYPES = {
    ADD_USER: 'ADD_USER',
    ADD_MESSAGE: 'ADD_MESSAGE',
    GET_CONVERSATIONS: 'GET_CONVERSATIONS',
    GET_MESSAGES: 'GET_MESSAGES',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES',
    DELETE_MESSAGES: 'DELETE_MESSAGES',
    DELETE_CONVERSATION: 'DELETE_CONVERSATION',
    CHECK_ONLINE_OFFLINE: 'CHECK_ONLINE_OFFLINE'
}

